# Generated by Django 4.0.2 on 2022-04-08 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_author_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='name',
            new_name='author_name',
        ),
    ]
