# Generated by Django 4.0.2 on 2022-04-08 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_name_author_author_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='name',
            new_name='book_name',
        ),
    ]
